### ISSUE TITLE
It must be possible to show a popup context menu in the navigation tree to allow you to execute options like delete etc.

### ISSUE THREAD

**Issue by tooh** [nestor-qa/nestor#65]

**Comment by kinow** [comment]
Implementing this, using the recommended library https://github.com/mar10/jquery-ui-contextmenu

Recommended by the developer of the fancytree.

**Comment by kinow** [comment]
The context menu is working! However, when the node is not editable (i.e. it has been executed before) then the menu is not displayed. It makes sense as the only options for now are Edit / Delete. Both disabled in the UI when the item is locked.

For a future release, we can hack the current icon, or add another icon or maybe change the font style, from locked nodes.

**Comment by kinow** [comment]
![gifrecord_2016-09-14_204216](https://cloud.githubusercontent.com/assets/304786/18505553/e4c608b0-7abb-11e6-9a1c-b33ca761d1d8.gif)
